/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "XYZWriter.h"
#include "../utils/Vector.h"
#include <cstdlib>
#include <sstream>

using namespace std;

namespace outputWriter {

XYZWriter::XYZWriter() {
	// TODO Auto-generated constructor stub

}

XYZWriter::~XYZWriter() {
	// TODO Auto-generated destructor stub
}

template<class Container>
void XYZWriter::plotParticles(Container* particles, const std::string& filename, int iteration) {
	std::ofstream file;
	stringstream strstr;
	strstr << filename << "_" << (iteration < 10 ? "000" : (iteration < 100 ? "00" : ( iteration < 1000 ? "0" : "") )) << iteration << ".xyz";

	file.open(strstr.str().c_str());
	long unsigned numPart = 0;
	for(typename Container::iterator iterator = particles->begin(); iterator.isValid();++iterator){
		++numPart;
	}
	file << numPart << endl;
	file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for file format doku." << endl;

	typename Container::iterator iterator = particles->begin();
	while (iterator.isValid()) {
		ParticleMS& p = *iterator;
		utils::Vector<double, 3> x = p.getR();
		file << "Ar ";
		file.setf(ios_base::showpoint);

		for (int i = 0; i < 3; i++) {
			file << x[i] << " ";
		}

		file << endl;
		iterator++;
	}

	file.close();
}

} // end namespace
