# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raffi/Documents/Bachelorarbeit/AutoPas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raffi/Documents/Bachelorarbeit/AutoPas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raffi/Documents/Bachelorarbeit/AutoPas/CMakeFiles /home/raffi/Documents/Bachelorarbeit/AutoPas/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raffi/Documents/Bachelorarbeit/AutoPas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) -f AutoPas/CMakeFiles/doc_doxygen.dir/build.make AutoPas/CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

#=============================================================================
# Target rules for targets named clangformat

# Build rule for target.
clangformat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clangformat
.PHONY : clangformat

# fast build rule for target.
clangformat/fast:
	$(MAKE) -f AutoPas/CMakeFiles/clangformat.dir/build.make AutoPas/CMakeFiles/clangformat.dir/build
.PHONY : clangformat/fast

#=============================================================================
# Target rules for targets named autopas

# Build rule for target.
autopas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autopas
.PHONY : autopas

# fast build rule for target.
autopas/fast:
	$(MAKE) -f AutoPas/src/CMakeFiles/autopas.dir/build.make AutoPas/src/CMakeFiles/autopas.dir/build
.PHONY : autopas/fast

#=============================================================================
# Target rules for targets named basic

# Build rule for target.
basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic
.PHONY : basic

# fast build rule for target.
basic/fast:
	$(MAKE) -f AutoPas/examples/basic/CMakeFiles/basic.dir/build.make AutoPas/examples/basic/CMakeFiles/basic.dir/build
.PHONY : basic/fast

#=============================================================================
# Target rules for targets named md-flexible

# Build rule for target.
md-flexible: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 md-flexible
.PHONY : md-flexible

# fast build rule for target.
md-flexible/fast:
	$(MAKE) -f AutoPas/examples/md-flexible/CMakeFiles/md-flexible.dir/build.make AutoPas/examples/md-flexible/CMakeFiles/md-flexible.dir/build
.PHONY : md-flexible/fast

#=============================================================================
# Target rules for targets named md-main

# Build rule for target.
md-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 md-main
.PHONY : md-main

# fast build rule for target.
md-main/fast:
	$(MAKE) -f AutoPas/examples/md/CMakeFiles/md-main.dir/build.make AutoPas/examples/md/CMakeFiles/md-main.dir/build
.PHONY : md-main/fast

#=============================================================================
# Target rules for targets named sph-main

# Build rule for target.
sph-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sph-main
.PHONY : sph-main

# fast build rule for target.
sph-main/fast:
	$(MAKE) -f AutoPas/examples/sph/CMakeFiles/sph-main.dir/build.make AutoPas/examples/sph/CMakeFiles/sph-main.dir/build
.PHONY : sph-main/fast

#=============================================================================
# Target rules for targets named sph-diagram-generation

# Build rule for target.
sph-diagram-generation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sph-diagram-generation
.PHONY : sph-diagram-generation

# fast build rule for target.
sph-diagram-generation/fast:
	$(MAKE) -f AutoPas/examples/sphDiagramGeneration/CMakeFiles/sph-diagram-generation.dir/build.make AutoPas/examples/sphDiagramGeneration/CMakeFiles/sph-diagram-generation.dir/build
.PHONY : sph-diagram-generation/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f AutoPas/tests/CMakeFiles/gtest.dir/build.make AutoPas/tests/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) -f AutoPas/tests/testAutopas/CMakeFiles/runTests.dir/build.make AutoPas/tests/testAutopas/CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

#=============================================================================
# Target rules for targets named MolSim

# Build rule for target.
MolSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MolSim
.PHONY : MolSim

# fast build rule for target.
MolSim/fast:
	$(MAKE) -f molsim/CMakeFiles/MolSim.dir/build.make molsim/CMakeFiles/MolSim.dir/build
.PHONY : MolSim/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc_doxygen"
	@echo "... clangformat"
	@echo "... autopas"
	@echo "... basic"
	@echo "... md-flexible"
	@echo "... md-main"
	@echo "... sph-main"
	@echo "... sph-diagram-generation"
	@echo "... gtest"
	@echo "... runTests"
	@echo "... MolSim"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

